
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443


FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG BUILD_CONFIGURATION=Release
ENV NUGET_USERNAME
ENV NUGET_GITHUB_PAT


WORKDIR /src


COPY ["Skuata-app/package.json", "Skuata-app/"]
COPY ["Skuata-app.client.csproj", ""]

#Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs



RUN dotnet nuget add source \
    --username $NUGET_USERNAME \
    --password $NUGET_GITHUB_PAT \
    --store-password-in-clear-text \
    --name github "https://nuget.pkg.github.com/SoftElsie/index.json"

COPY . .

RUN dotnet restore "Skuata-app.client.csproj" \
    --source "https://nuget.pkg.github.com/SoftElsie/index.json" \
    --source "https://api.nuget.org/v3/index.json"

    #Verify Node.js installation
RUN node --version 



 
WORKDIR "/src"

RUN dotnet build "Skuata-app.client.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish  -o /app/publish 

FROM base AS final
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:80
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Skuata-app.client.dll"]





